Ejercicio de http
utnfrrottads/angular9-example pull request #31
Opened 2020-06-30 23:26 UTC by Gabriel-Campitelli

Buenas noches profe, después de renegar un poco pude subir los cambios y hacer el pull request.

La duda que tengo es: luego de apretar el botón para agregar comentarios TRES veces, se realiza el posteo del comentario, pero dónde le estoy errando? Por qué?

Funciona la aplicación, pero no como quisiera.

Saludos,
Gabriel.

2020-06-30 23:47 UTC, Gabriel-Campitelli commented
![image](https://user-images.githubusercontent.com/53315236/86187725-d83e7a00-bb12-11ea-89c6-50a4f9a5c28d.png)

Adjunto imagen del error que le comentaba arriba.

2020-07-15 19:10 UTC, aotaduy requested changes
Fijate si podes cambiar lo que te dije en la partge de mandadr el comentario, es un tema de sincronia, tratqat de hacer todo dentro del subscribe del liogin y depsues separalo en funciones. 
porque el this.http.post() retorna inmeditamente 
y todavia no tenes el usuario 

Fijate en los ejemplos de los otros PR ahipoes ver como lo hacen

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles.service.ts
> +  respuesta:any;
el codigo deberia estar todod en ingles para evitar spanglish

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles.service.ts
> +    return this.usrReturned.user;
este reuturn no te3 va a devolver el usuario 
ya que la operacion es asincrona

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles/articles.component.ts
> +        this.articles[i] = response.articles[i]
no hace falta copiarlos uno por uno se puede usar Array.slice

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles/articles.component.ts
> +    console.log(userReturned);
aca tenes el problema de sincronia de antes
tenes que devolver el observable y hacer todo en el subscribe o sino primero loguearte con un boton, guardare el uisuaro 
y despues usarlo para mandar el comentario.

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles/articles.component.ts
> +    var comentario = {"comment":{
evitemos var en trypescript y es6 mejor let y constt

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles/articles.component.ts
> +    var comentario = {"comment":{
tambien las doble comillas mejor simples

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles/articles.component.ts
> +    var comentario = {"comment":{
para las keys de un objeto no hacen falta las comillas a menjos que tengas caracteres especiales o nombres que no fiorma  el nombde re una variable valida

2020-07-15 19:10 UTC, aotaduy commented on src/app/articles/workspace(prueba).code-workspace
> +	"folders": [
?!

2020-07-16 14:09 UTC, Gabriel-Campitelli commented on src/app/articles/articles.component.ts
> +    console.log(userReturned);
Gracias profe! Ahí estaba el problema

2025-09-11 20:48 UTC, closed without merging